---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install apache2 package
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: install support for PHP
    ansible.builtin.dnf:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Fedora"
