---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package and PHP
    ansible.builtin.apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_os_family == "Debian"

  - name: install httpd package and PHP
    ansible.builtin.dnf:
      update_cache: yes
      name:
        - httpd
        - php
      use_backend: dnf4
      state: latest
    when: ansible_os_family== "RedHat"
