---
- hosts: all
  name: Install apache2 and php
  become: true
  tasks:

    - name: Install apache2 package and PHP
      ansible.builtin.package:
        update_cache: true
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
