- name: Install apache on web servers
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"

- name: Ensure apache is running
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
  when: ansible_os_family == "Redhat"

- name: Change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin poppyss@puppyplayground.pup
  when: ansible_os_family == "RedHat"
  notify: restart_apache

- name: Change email address for admin
  tags: apache,ubuntu
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin poppyss@puppyplayground.pup
  when: ansible_os_family == "Debian"
  notify: restart_apache

- name: Copy html file for default_site
  tags: apache,ubuntu,fedora,httpd
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0664"
