- name: Create user
  tags: always
  ansible.builtin.user:
    name: sally
    groups: root

- name: Add sudoers file for sally
  tags: always
  ansible.builtin.copy:
    src: sudoer_sally
    dest: /etc/sudoers.d/sally
    owner: root
    group: root
    mode: "0440"

- name: Add ssh key for sally user
  tags: always
  ansible.builtin.authorized_key:
    user: sally
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINVHhkMYF2rs1MnuowYocfPoSEr0JIAOzYFsGdVfNm2r bill@BillsZEN"

- name: Configure ssh based on template
  ansible.builtin.template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: "0664"
  notify: restart_sshd

- name: Install ansible
  tags: always
  ansible.builtin.package:
    name: ansible-core
